/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOY
 */
public class converter extends javax.swing.JFrame {

    /**
     * Creates new form converter
     */
    public converter() {
        initComponents();
        this.setTitle("Converter");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb3 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb1 = new javax.swing.JComboBox<>();
        output = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        input = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb3.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 300, 42));

        cb2.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 300, 42));

        cb1.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperature", "Leap Year" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 636, 48));

        output.setEditable(false);
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        output.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 638, 42));

        jButton1.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton1.setText("find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 200, 50));

        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 638, 42));

        jLabel2.setFont(new java.awt.Font("Open Sans Semibold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Input any Temperature or Year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, 40));

        jLabel3.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("powered by CTRL' Z '");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        
        if(cb1.getSelectedItem().toString()=="Leap Year")
        {
            cb2.setVisible(false); cb3.setVisible(false);
        }
        else
        {
            cb2.setVisible(true); cb3.setVisible(true);  
        }
        
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String s1="", s2="";
        double x=0,y=0;
        
        s1 = input.getText(); 
        x = Double.parseDouble(s1);
        
        if (cb1.getSelectedItem().toString()=="Temperature")
        {
            if (cb2.getSelectedItem().toString()=="Celsius")
            {
                if (cb3.getSelectedItem().toString()=="Celsius")
                {
                    y= x; 
                    s2= String.format("''%.2f'' Celsius", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Fahrenheit")
                {
                    y= (x*1.8)+32 ;
                    s2= String.format("''%.2f'' Fahrenheit", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Kelvin")
                {
                    y= (x + 273.15);
                    s2= String.format("''%.2f'' Kelvin", y);
                    output.setText(s2);
                }
                
            }
            //////////
            else if (cb2.getSelectedItem().toString()=="Fahrenheit")
            {
                if (cb3.getSelectedItem().toString()=="Celsius")
                {
                    y= (x-32) / 1.8 ;
                    s2= String.format("''%.2f'' Celsius", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Kelvin")
                {
                    y= ((x-32)*5/9) + 273.15;
                    s2= String.format("''%.2f'' Kelvin", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Fahrenheit")
                {
                    y= x;
                    s2= String.format("''%.2f'' Fahrenheit", y);
                    output.setText(s2);
                }
            }
            /////////////////////
            else if (cb2.getSelectedItem().toString()=="Kelvin")
            {
                if (cb3.getSelectedItem().toString()=="Fahrenheit")
                {
                    y= (x-273.15) * 1.8 + 32 ;
                    s2= String.format("''%.2f'' Fahrenheit", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Celsius")
                {
                    y= x-273.15;
                    s2= String.format("''%.2f'' Celsius", y);
                    output.setText(s2);
                }
                else if (cb3.getSelectedItem().toString()=="Kelvin")
                {
                    y= x;
                    s2= String.format("''%.2f'' Kelvin", y);
                    output.setText(s2);
                }
            }
            
        }
        else if (cb1.getSelectedItem().toString()=="Leap Year")
        {
            if(x%400==0)
            {
                s2= String.format("''%.0f'' is Leap year...\n", x);
                output.setText(s2);
            }//end of 1st if
            else
            {
                if(x%100==0)
                {
                    s2= String.format("''%.0f' is not Leap year...\n", x);
                    output.setText(s2);
                }//end of 2nd if
                else
                {
                    if(x%4==0)
                    {
                        s2= String.format("''%.0f'' is Leap year...\n", x);
                        output.setText(s2);
                    }//end of 3rd if
                    else
                    {
                        s2= String.format("''%.0f'' is not Leap year...\n", x);
                        output.setText(s2);
                    }//end of 3rd else
                }//end of 2nd else
            }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JFormattedTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField output;
    // End of variables declaration//GEN-END:variables
}
